Multipackage updates to docs
SecondCloset/parcel-api-docs pull request #6
Opened 2023-09-13 15:58 UTC by harveydoodle

2023-09-13 15:59 UTC, jhrams approved these changes

2023-09-13 16:08 UTC, helenjw commented on swagger.yml
> +                  description: The unit of measurement for the package. Can be either `kg`, `g` or `lb`.
we still only accept kg or lb

2023-09-13 16:08 UTC, helenjw commented on swagger.yml
> +          description: 'Successful response'
A successful response on order create now looks like this:
```
  {
	"id": "ESN9NY5IE6OU",
	"packages": [
		{
			"trackingNumber": "FTWSSSZ7UJEB",
			"sizeOptions": {
				"length": 0,
				"width": 0,
				"height": 0,
				"unit": "inch"
			},
			"weightOptions": {
				"weight": 1,
				"unit": "lb"
			}
		}
	]
}
```

2023-09-13 16:14 UTC, helenjw commented on swagger.yml
>      x-summary: Update the packages in an order along with their dimensions and weight.
I think we should also add somewhere in the docs that the user cant change the number of packages

2023-09-14 17:08 UTC, Helenjw commented
Oh, we also need to update the return payload of the tracking backend. It will now include an extra field "trackingNumber"
```
{
			"eventName": "GEOCODED",
			"timestamp": 1679037498774,
			"trackingNumber": "OKWIVCXADDHW",
			"eventDescription": "Address is valid"
}
```

2023-09-15 17:30 UTC, xenyal approved these changes

2023-09-15 17:34 UTC, Helenjw requested changes

2023-09-15 17:34 UTC, helenjw commented on swagger.yml
> +                  description: The unit of measurement for the package. Can be either `kg`, `g` or `lb`.
remove 'g'

2023-09-15 17:34 UTC, helenjw commented on swagger.yml
> +              description: The unit of measurement for the package. Can be either `kg`, `g` or `lb`.
remove g

2023-09-15 17:34 UTC, Helenjw commented on swagger.yml
> +          required: true
optional, default false

2023-09-15 17:35 UTC, Helenjw commented on swagger.yml
> +          required: true
Also, Tracking Response.timeline now includes a new field `trackingNumber` which needs to be represented in the docs

2023-09-15 17:47 UTC, Helenjw commented on swagger.yml
> +      packages:
I don't think the tracking response gives back the package details. It just gives the package count

2023-09-15 17:47 UTC, Helenjw commented on swagger.yml
> +              description: Tracking number of package for the event
this can be orderId or package tracking number

2023-09-15 17:55 UTC, Helenjw approved these changes

2023-09-15 17:57 UTC, merged